[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["ffmpeg", "imagemagick"]
aptPkgs = []

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install imageio-ffmpeg",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn web_app_multiuser:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --preload"
